# Generated by Django 2.1 on 2018-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_is_currentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_detailpage',
            field=models.BooleanField(default=False),
        ),
    ]
