# Generated by Django 2.1 on 2018-09-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_is_detailpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_detailpage',
        ),
    ]
